AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla Basica grupo de seguridad

Resources:
  SGSHHIVAN: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: SSHAccess
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
    

        
